/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hpp.ui;

import org.hpp.ui.ctrl.MainFormCtrl;

/**
 *
 * @author root
 */
public class MainForm extends javax.swing.JFrame {
    private MainFormCtrl formCtrl = new MainFormCtrl(this);

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplit = new javax.swing.JSplitPane();
        inputParamPanel = new javax.swing.JPanel();
        modelPanel = new javax.swing.JPanel();
        modelSplit = new javax.swing.JSplitPane();
        mapScrollPane = new javax.swing.JScrollPane();
        mapPanelBackground = new javax.swing.JPanel();
        mapPanel = new org.hpp.ui.component.MapPanel();
        outputParamPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        mapMenu = new javax.swing.JMenu();
        genMapMenu = new javax.swing.JMenuItem();
        saveMapMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hydropower plant model");
        setLocationByPlatform(true);

        mainSplit.setDividerLocation(150);
        mainSplit.setDividerSize(10);
        mainSplit.setOneTouchExpandable(true);

        javax.swing.GroupLayout inputParamPanelLayout = new javax.swing.GroupLayout(inputParamPanel);
        inputParamPanel.setLayout(inputParamPanelLayout);
        inputParamPanelLayout.setHorizontalGroup(
            inputParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        inputParamPanelLayout.setVerticalGroup(
            inputParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        mainSplit.setLeftComponent(inputParamPanel);

        modelSplit.setDividerLocation(450);
        modelSplit.setDividerSize(10);
        modelSplit.setOneTouchExpandable(true);

        mapPanel.setAutoscrolls(true);

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mapPanelBackgroundLayout = new javax.swing.GroupLayout(mapPanelBackground);
        mapPanelBackground.setLayout(mapPanelBackgroundLayout);
        mapPanelBackgroundLayout.setHorizontalGroup(
            mapPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPanelBackgroundLayout.createSequentialGroup()
                .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        mapPanelBackgroundLayout.setVerticalGroup(
            mapPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPanelBackgroundLayout.createSequentialGroup()
                .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 142, Short.MAX_VALUE))
        );

        mapScrollPane.setViewportView(mapPanelBackground);

        modelSplit.setLeftComponent(mapScrollPane);

        javax.swing.GroupLayout outputParamPanelLayout = new javax.swing.GroupLayout(outputParamPanel);
        outputParamPanel.setLayout(outputParamPanelLayout);
        outputParamPanelLayout.setHorizontalGroup(
            outputParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        outputParamPanelLayout.setVerticalGroup(
            outputParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        modelSplit.setRightComponent(outputParamPanel);

        javax.swing.GroupLayout modelPanelLayout = new javax.swing.GroupLayout(modelPanel);
        modelPanel.setLayout(modelPanelLayout);
        modelPanelLayout.setHorizontalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modelSplit)
        );
        modelPanelLayout.setVerticalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modelSplit)
        );

        mainSplit.setRightComponent(modelPanel);

        fileMenu.setText("File");

        jMenuItem1.setText("jMenuItem1");
        fileMenu.add(jMenuItem1);
        fileMenu.add(jSeparator1);

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenu);

        mainMenu.add(fileMenu);

        mapMenu.setText("Map");

        genMapMenu.setText("Generate...");
        genMapMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genMapMenuActionPerformed(evt);
            }
        });
        mapMenu.add(genMapMenu);

        saveMapMenu.setText("Save to file");
        saveMapMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMapMenuActionPerformed(evt);
            }
        });
        mapMenu.add(saveMapMenu);

        mainMenu.add(mapMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplit)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplit)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genMapMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genMapMenuActionPerformed
        formCtrl.generateMap(400, 400, 5, 100, 1, 4, 1, 2);
        formCtrl.paintMap();
    }//GEN-LAST:event_genMapMenuActionPerformed

    private void saveMapMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMapMenuActionPerformed
        formCtrl.saveMapToFile("map.png");
    }//GEN-LAST:event_saveMapMenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        formCtrl.exitApp();
    }//GEN-LAST:event_exitMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem exitMenu;
    public javax.swing.JMenu fileMenu;
    public javax.swing.JMenuItem genMapMenu;
    public javax.swing.JPanel inputParamPanel;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JMenuBar mainMenu;
    public javax.swing.JSplitPane mainSplit;
    public javax.swing.JMenu mapMenu;
    public org.hpp.ui.component.MapPanel mapPanel;
    public javax.swing.JPanel mapPanelBackground;
    public javax.swing.JScrollPane mapScrollPane;
    public javax.swing.JPanel modelPanel;
    public javax.swing.JSplitPane modelSplit;
    public javax.swing.JPanel outputParamPanel;
    public javax.swing.JMenuItem saveMapMenu;
    // End of variables declaration//GEN-END:variables
}
